const express = require(express);
const mongoose = reuire('mongoose');
const userRoutes = require('./routes/userRoutes');
 const connectDB = require('./config/db');
  const app = express(); 
   app,use( express.json());
   connectDB();
   app.use('/api',userRoutes);
   const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));